[package]
name = "mr-mime-generator"
version = "0.1.0"
edition = "2018"

[dependencies]
fastrand = "1.8.0"
heck = "0.4.0"
intern-str = { version = "0.1", features = ["builder"] }
intern-str-codegen = { version = "0.1.2" }
memchr = "2.5.0"
