[package]
name = "mr-mime"
version = "0.1.0"
edition = "2018"

[dependencies]
intern-str = { version = "0.1", default-features = true }

[workspace]
members = ["generator"]

[features]
default = ["std"]
alloc = []
std = ["alloc"]

[build-dependencies]
autocfg = "1.1.0"
